apiVersion: v2
name: corda
description: A Helm chart for Corda
type: application
version: 0.4.0-beta.3-HC.1
appVersion: unstable
dependencies:
- name: corda-lib
  version: 0.1.0
  repository: file://../corda-lib
