[versions]
kotlinVersion = "1.8.21"

bouncycastleVersion = "1.77"

# REST dependency versions
javalinVersion = "4.6.8"
# This version of Jetty must be the same major version as used by Javalin, please see above.
# Once Javalin version is upgraded to the latest, this override may be removed.
jettyVersion = "9.4.53.v20231009"

log4jVersion = "2.22.1"
# SLF4J cannot be ugraded to 2.x due to CorDapps requiring the 1.7 <= x < 2.0
slf4jVersion = { strictly = "1.7.36" }
# The CLI plugins use SLF4J version 2 because PF4j requires it
# Since slf4jVersion is "strictly" enforced from `corda-api`, in order to override version we need to specify
# version strictly here as well
slf4jV2Version = { strictly = "2.0.6" }

# Testing
assertjVersion = "3.25.1"
junitVersion = "5.10.1"
mockitoVersion = "5.9.0"
mockitoKotlinVersion = "5.2.1"

# Plugins
gradleDataVersion = "1.12.1"
gradleEnterpriseVersion = "3.16.1"
detektVersion = "1.23.4"
dependencyCheckVersion = "0.51.0"
snykVersion = "0.5.1"
cyclonedxVersion = "1.8.1"
dokkaVersion = "1.9.10"
testLoggerVersion = "4.0.0"

[libraries]
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertjVersion" }
bouncycastle-pkix = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bouncycastleVersion" }
bouncycastle-prov = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastleVersion" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitVersion" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitVersion" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitVersion" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitVersion" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinVersion" }
kotlin-stdlib-common = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-common", version.ref = "kotlinVersion" }
kotlin-stdlib-jdk7 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk7", version.ref = "kotlinVersion" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlinVersion" }
kotlin-osgi-bundle = { group = "org.jetbrains.kotlin", name = "kotlin-osgi-bundle", version.ref = "kotlinVersion" }
kotlin-reflect= { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlinVersion" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinVersion" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4jVersion" }
log4j-layout-json = { group = "org.apache.logging.log4j", name = "log4j-layout-template-json", version.ref = "log4jVersion" }
log4j-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j-impl", version.ref = "log4jVersion" }
log4j-slf4j2 = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4jVersion" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoVersion" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlinVersion" }
javalin = { group = "io.javalin", name = "javalin-osgi", version.ref = "javalinVersion" }
jetty-server = { group = "org.eclipse.jetty", name = "jetty-server", version.ref = "jettyVersion" }
jetty-xml = { group = "org.eclipse.jetty", name = "jetty-xml", version.ref = "jettyVersion" }
jetty-websocket-servlet = { group = "org.eclipse.jetty.websocket", name = "websocket-servlet", version.ref = "jettyVersion" }
jetty-websocket-server = { group = "org.eclipse.jetty.websocket", name = "websocket-server", version.ref = "jettyVersion" }
jetty-websocket-client = { group = "org.eclipse.jetty.websocket", name = "websocket-client", version.ref = "jettyVersion" }
jetty-http2-server = { group = "org.eclipse.jetty.http2", name = "http2-server", version.ref = "jettyVersion" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jVersion" }
slf4j-jul = { group = "org.slf4j", name = "jul-to-slf4j", version.ref = "slf4jVersion" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4jVersion" }
slf4j-v2-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jV2Version" }

gradle-enterprise = { group = "com.gradle", name = "gradle-enterprise-gradle-plugin", version.ref = "gradleEnterpriseVersion" }

[bundles]
bouncycastle = ["bouncycastle-prov", "bouncycastle-pkix"]
jetty = ["jetty-server", "jetty-xml", "jetty-websocket-servlet", "jetty-websocket-server"]
test = ["junit", "junit-api", "junit-params", "mockito-core", "mockito-kotlin", "assertj-core", "kotlin-test"]
test-runtime = ["junit-engine", "junit-platform"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlinVersion" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlinVersion" }
gradle-data = { id = "com.gradle.common-custom-user-data-gradle-plugin", version.ref = "gradleDataVersion" }
gradle-enterprise = { id = "com.gradle.enterprise", version.ref = "gradleEnterpriseVersion" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektVersion" }
dependency-check-versions = { id = "com.github.ben-manes.versions", version.ref = "dependencyCheckVersion" }
snyk = { id = "io.snyk.gradle.plugin.snykplugin", version.ref = "snykVersion" }
cyclonedx-bom = { id = "org.cyclonedx.bom", version.ref = "cyclonedxVersion" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaVersion" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "testLoggerVersion" }
