{
  "org.corda.interop/platform/hello-interop/v1.0": {
    "say-hello": "com.net.corda.flow.SayHelloFlow",
    "get-balance": "com.net.corda.flow.GetBalanceFlow"
  },
  "org.corda.interop/platform/tokens/v1.0": {
    "get-balance": "com.net.corda.flow.GetBalanceFlow",
    "get-token": "com.net.corda.flow.GetTokenFlow"
  }
}
