name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '0 0 * * 1-5'

jobs:
  remove-stale-prs:
    name: Remove stale PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.0.0
        with:
          debug-only: false
          exempt-pr-labels: 'DO_NOT_CLOSE'
          stale-pr-message: 'This PR is stale because it has been open 7 days with no activity. Remove the `Stale` label or add a comment - otherwise this will be closed in 7 days.'
          close-pr-message: 'This PR was closed because it has been stale for 7 days with no activity.'
          days-before-issue-stale: -1
          days-before-issue-close: -1
          days-before-pr-stale: 7
          days-before-pr-close: 7
