name: 'Remove stale branches'
on:
  schedule:
    - cron: '0 0 * * 1-5'

jobs:
  remove-stale-branches:
    name: Remove stale branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v2.0.1
        with:
          dry-run: false
          ignore-unknown-authors: true
          default-recipient: "corda-jenkins-ci02"
          days-before-branch-stale: 30
          days-before-branch-delete: 14
          stale-branch-message: "@{author} The branch [{branchName}]({branchUrl}) hasn't been updated in the last 30 days and is marked as stale. It will be removed in 14 days.\r\nIf you want to keep this branch around, delete this comment or add new commits to this branch."
          exempt-protected-branches: true
          exempt-branches-regex: "^(release\\/|feature\\/|poc\\/|merge-release\\/).*"
          operations-per-run: 30
